### ISSUE TITLE
是否可以支持读取excel中的图片

### ISSUE THREAD

**Issue by RexH0** [wangguanquan/eec#168]

**Comment by wangguanquan** [comment]
图片可以读的，但是应该以什么形式返回呢？File or IO?

**Comment by RexH0** [comment]
配置一个文件路径，将文件写到硬盘，单元格的位置返回文件位置，这样可能会理想一点

发自我的iPhone

**Comment by wangguanquan** [comment]
好提议

**Comment by RexH0** [comment]
上周用poi实现了一个获取图片的，5mb的文件就内存溢出，效率很低，而且兼容性很差，今天看这个项目，看了很久没看懂怎么改才能获取图片😂

发自我的iPhone

**Comment by wangguanquan** [comment]
xlsx较简单，图片路径在`xl/media/`下，读取的时候需要解析`xl/drawings/`包下的文件，里面有图片的位置等信息，配合各sheet的`<drawing/>`就可以拿到了
xls麻烦一点，方法都一样，只是xls是二进制格式的，eec-e3-support暂时没有开源

**Comment by wangguanquan** [comment]
更新代码切换到fix#168分支，本地install应该就可以读取xlsx中的图片了，使用方法参照： https://github.com/wangguanquan/eec/wiki/如何读取Excel中的图片

**Comment by RexH0** [comment]
![image](https://user-images.githubusercontent.com/11851142/116050516-275d2900-a6aa-11eb-8a67-7035fa4819de.png)
部署到tomcat中时无法访问图片的路径
java.lang.IllegalAccessError: tried to access field org.ttzero.excel.reader.Drawings$Picture.localPath
这是啥原因？

**Comment by RexH0** [comment]
![image](https://user-images.githubusercontent.com/11851142/116050516-275d2900-a6aa-11eb-8a67-7035fa4819de.png)
部署到tomcat中时无法访问图片的路径
java.lang.IllegalAccessError: tried to access field org.ttzero.excel.reader.Drawings$Picture.localPath
这是啥原因？

**Comment by RexH0** [comment]
好像是因为没有权限访问那个目录，怎么授权？

**Comment by wangguanquan** [comment]
需要看一下是读取没有权限还是写入没有权限，看上去应该是你指定的目标文件夹没有权限，可以给tomcat用户设置权限

**Comment by RexH0** [comment]
临时文件写进去了，读的时候无权限，mac springboot 内嵌tomcat启动的，main函数启动可以

**Comment by RexH0** [comment]
解决了，不是权限问题，Drawings.Picture这个类的定义 现在不怎么友好，这是一个interface的内部类，现在如果我要在其他类里面使用封装方法使用，包名必须为org.ttzero.excel.reader 否则是无法访问这个类的

**Comment by wangguanquan** [comment]
嗯，要把Drawings改为public，定义有问题。

**Comment by wangguanquan** [comment]
v0.4.13
