### ISSUE TITLE
请问一下 怎么设置单元格的居中

### ISSUE THREAD

**Issue by clockworm** [wangguanquan/eec#184]
![QQ图片20210604161433](https://user-images.githubusercontent.com/12193979/120769702-f5b06b00-c54f-11eb-959b-73703ccb3727.png)

该图中 如果单元格的数据
如果为空 导致单元格视觉错位,请问有什么办法吗?

**Comment by clockworm** [comment]
这是我的代码,请问该怎么修改,谢谢
new Workbook("数据报表", "SJT").addSheet(new ListSheet<>(datas).fixSize()).writeTo(out);

**Comment by wangguanquan** [comment]
能把数据数据给我一份吗（给假数据就行），我不知道什么情况下会出现错位的情况。可以使用JSON数组的格式发我邮箱 guanquan.wang@yandex.com

**Comment by clockworm** [comment]
我看了一下不是錯位,是数据的单元格位置出现了问题,&nbsp;&nbsp; 同一个单元格里的数据有些数据在左边,有些在中间




数据和导出文件请在附件查看,谢谢

**Comment by wangguanquan** [comment]
已经收到了你的附件，方便把类定义给我吗？

**Comment by wangguanquan** [comment]
你可以将版本回退到0.4.10，那个版本没有此问题。感谢你的反馈

**Comment by wangguanquan** [comment]
你可以将版本回退到0.4.10，那个版本没有此问题。感谢你的反馈

**Comment by clockworm** [comment]
感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月4日(星期五) 晚上8:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wangguanquan/eec] 请问一下 怎么设置单元格的居中 (#184)





 
你可以将版本回退到0.4.10，那个版本没有此问题。感谢你的反馈

**Comment by clockworm** [comment]
再次请教个问题,怎么去掉背景色.

**Comment by clockworm** [comment]
cancelOddFill()  谢谢

**Comment by wangguanquan** [comment]
是的，你找到正确的方式。
