### ISSUE TITLE
ExcelColumn注解希望新增枚举类型的处理,谢谢

### ISSUE THREAD

**Issue by clockworm** [wangguanquan/eec#192]
```
@ExcelColumn(value="配送方式",  type=ShippingTypeEnum.class,  field="message")
private ShippingTypeEnum shippingType;
```
```
public enum ShippingTypeEnum {

    FACTORY_SHIPPING("Z001","厂家配送"),

    INVENTORY_SHIPPING("Z002","仓库配送"),
    ;

    private final String code;
    private final String message;

    ShippingTypeEnum(String code, String message) {
        this.code = code;
        this.message = message;
    }
}
```
导出枚举的时候希望可以支持下枚举,增加type类型和filed值,谢谢

**Comment by wangguanquan** [comment]
暂时你可以覆写ShippingTypeEnum类的toString方法，像下面这样
```
@Override
public String toString() {
    return message;
}
```

**Comment by clockworm** [comment]
好的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月28日(星期三) 晚上10:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wangguanquan/eec] ExcelColumn注解希望新增枚举类型的处理,谢谢 (#192)





 
暂时你可以覆写ShippingTypeEnum类的toString方法，像下面这样
 @Override public String toString() {     return message; }

**Comment by 344020353** [comment]
已测试 可行 👍

**Comment by wangguanquan** [comment]
可参考 [未知的数据类型](https://github.com/wangguanquan/eec/wiki/1-%E5%AF%BC%E5%87%BAExcel#%E6%9C%AA%E7%9F%A5%E7%9A%84%E6%95%B0%E6%8D%AE%E7%B1%BB%E5%9E%8B)
