### ISSUE TITLE
新建一个xlsx文件，建两个sheet ,删除第一个sheet 后，读取到的剩余sheet ,index 为2，怎么能让sheet删除后index从1开始

### ISSUE THREAD

**Issue by RexH0** [wangguanquan/eec#193]
![image](https://user-images.githubusercontent.com/11851142/128450573-b627e19b-dca6-43e8-ae53-7c1229951502.png)
[工作簿2.xlsx](https://github.com/wangguanquan/eec/files/6942764/2.xlsx)

**Comment by wangguanquan** [comment]
这里的index准确的值应该是worksheet的id，而不是字面上worksheet在整个workbook的下标的意思，*有歧义*。

我会在worksheet对象里添加一个`id`字段，将index改为index of workbook的值。

临时处理：你可以直接拿list的下标。

另外，好后直接调用`ExcelReader#all()`方法，而不是使用`ExcelReader.sheets().collect(Collectors.toList())`。`#sheets()`方法是为流设计的，最好使用流式处理。

**Comment by RexH0** [comment]
List 的下标其实无法解决问题，因为读出来的sheets[]在list中的顺序并不是在工作簿里面看到的顺序
![image](https://user-images.githubusercontent.com/11851142/128466369-bc9c3e2e-41b5-46b4-ae9f-01aa4ad4b81e.png)
![image](https://user-images.githubusercontent.com/11851142/128466478-2026f9d6-be70-4460-98bb-007540af917f.png)
读取到数组中的时候就是index那个顺序

**Comment by wangguanquan** [comment]
好像是的，我默认按id进行排序了。最近会更新一个版本修复。

如果比较紧急的话可以fork本项目，然后在ExcelReader类里找到read方法找到排序的地方注释掉，然后提一个PR合并。
