### ISSUE TITLE
内嵌的guava可能会与独立引用的guava冲突

### ISSUE THREAD

**Issue by MrLiuzy** [wangguanquan/eec#200]
由于项目当中依赖了guava，在使用eec时，发现它包含了部分guava的代码。个人有个疑问，为什么不将内嵌的guava相关代码的包路径进行重命名，这样的话能够保证不会因为独立引入了guava而导致类冲突？

**Comment by wangguanquan** [comment]
当初考虑eec仅用了过滤器，依赖guava包太大所以才内嵌。你能把冲突错误发一下吗？

**Comment by wangguanquan** [comment]
下一版考虑将内嵌guava移掉，直接在pom文件依赖

**Comment by MrLiuzy** [comment]
之前遇到过相同的情况引发的事故，因为某个jar内嵌了其他jar的代码，导致某次重启项目后运行报错，提示method不存在。所以对这种情况比较敏感。因为类加载器到底会加载到哪个jar中的类，全靠运气，我们在测试的时候，一切正常，但是到正式环境重启就会偶现该异常。
如果考虑guava不向后兼容的话，那么，独立guava版本高于eec中内嵌的guava，如果classloader从eec中加载了对应的guava类，那么就可能会导致引发method不存在的异常。
guava是使用的apache 2.0 协议，允许修改源代码，个人认为将eec内嵌的guava的包名重命名是一个比较好的方式，这样就不会受到独立guava的影响了。

**Comment by wangguanquan** [comment]
考虑得很周全！下一版考虑将内嵌guava移掉。
