### ISSUE TITLE
你好，可以提供自动计算列宽时屏蔽某些列的注解吗

### ISSUE THREAD

**Issue by liuc-c** [wangguanquan/eec#201]
在自动计算列宽的时候，有些列个别属性很长，其他普遍都很短，比如详细地址，就会出现下面这种情况，希望可以有一个在自动计算列宽时忽略某些列的注解。

![image](https://user-images.githubusercontent.com/29280376/129855651-7053f2da-78bf-4131-a519-abb6893ba277.png)

**Comment by wangguanquan** [comment]
好提议，可以在HeaderStyle里添加width等属性。

临时的，你可以使用下面的方法修改
```
    new Workbook().setAutoSize(true).addSheet(new ListSheet<Entry>(list) {
            @Override
            public Column[] getHeaderColumns() {
                if (!headerReady) {
                    Column[] columns = super.getHeaderColumns();
                    for (Column column : columns) {
                        if ("详细地址".equals(column.name)) {
                            column.width = 10; // 详细地址设置固定列宽
                        }
                    }
                }
                return columns;
            }
        }).writeTo(Paths.get("d:/"));
```

你也可以参考wiki[高级特性](https://github.com/wangguanquan/eec/wiki/%E9%AB%98%E7%BA%A7%E7%89%B9%E6%80%A7) 实现自定义注解，可以自已定义一个列宽的注解。

v0.4.13版发版前未合并部分代码，使得EntryColumn访问权限被定义为包类可用，如果要实现自定义注解的话需要将自定ListSheet放在org.ttzero.excel.entity目录下

**Comment by liuc-c** [comment]
好的，谢谢👍

**Comment by wangguanquan** [comment]
v0.5.3版本增加maxWidth属性，在自适应列宽的场景可以控制列宽的最大值，[参考wiki](https://github.com/wangguanquan/eec/wiki/%E5%85%B3%E4%BA%8E%E8%87%AA%E9%80%82%E5%BA%94%E5%88%97%E5%AE%BD#%E6%88%B4%E4%B8%8A%E7%B4%A7%E7%AE%8D%E5%92%92%E5%90%A7)
