### ISSUE TITLE
您好，请问现在支持多行表头格式嘛

### ISSUE THREAD

**Issue by weirdoyj** [wangguanquan/eec#210]
请问自定义内容的多行表头如果实现，没找到对应的设置方法

**Comment by wangguanquan** [comment]
暂时没有这个功能，如果你对office有所了解的话可以自定义XMLWorksheetWriter然后覆写writeBefore和writeAfter方法，前者定表头，如果有合并单元格需要在writeAfter添加合并信息

**Comment by weirdoyj** [comment]
好的，多谢

**Comment by wangguanquan** [comment]
v0.5.3支持多表头 示例参考[WIKI](https://github.com/wangguanquan/eec/wiki)
