### ISSUE TITLE
The file format is incorrect or corrupted. [/xl/drawings/_rels/drawing1.xml.rels]

### ISSUE THREAD

**Issue by RexH0** [wangguanquan/eec#212]
导入xlsx读取图片报错
![image](https://user-images.githubusercontent.com/11851142/140683857-62a8696d-a798-4c85-aeff-04e614f0e307.png)
请提供邮箱我把模板发给你

**Comment by RexH0** [comment]
我怀疑是xlsx里面哪里格式有问题，但是我看不出来，麻烦帮忙看看

**Comment by wangguanquan** [comment]
邮件 guanquan.wang@yandex.com

**Comment by RexH0** [comment]
模板已发

**Comment by wangguanquan** [comment]
你发的文档是WPS写的，WPS并没有写/xl/drawings/_rels/drawing1.xml.rels文件，目前的代码需要兼容才行，我晚点给你写一段兼容代码，你可以fork本项目然后自行修改，deploy到私库即可使用。

**Comment by wangguanquan** [comment]
错怪WPS了，你的文档里的并非简单的图片，而是使用OLEObjects对象嵌入了phoneshop，没有办法直接读取为图片格式。

教参联接：https://docs.microsoft.com/zh-cn/office/vba/api/excel.oleobjects

你可以使用POI试着读一下，EEC暂时无法处理。

**Comment by RexH0** [comment]
好的，谢谢

**Comment by wangguanquan** [comment]
原始格式为EMF位置在 /xl/media/image1.emf ，各单元格展示的大小，位置信息在 /xl/drawings/vmlDrawing1.vml 以及 xl/embeddings/oleObject1~13.bin

**Comment by wangguanquan** [comment]
你用POI读取可行么？如果可行的话请贴一下测试代码和POI的版本，我看一下POI是如何处理的

**Comment by RexH0** [comment]
还没忙得过来用poi去试，目前暂时让用户不要用EMBED那种方式去插入图片

**Comment by wangguanquan** [comment]
优秀！！办法总比困难多，没办法改变工具就试着改变使用工具的人。
