### ISSUE TITLE
高级特性-自定义注解

### ISSUE THREAD

**Issue by danielv5** [wangguanquan/eec#225]
ListSheet.EntryColumn不是public的。在项目新建XxxxListSheet覆盖重写createColumn时编译错误。

**Comment by wangguanquan** [comment]
是的，最近将发布v0.4.14版本，新版本已修复此问题。

如果紧急的话可以fork本项目，使用命令`mvn deploy` 到私库或者`mvn install`到本地

**Comment by wangguanquan** [comment]
v0.4.14已发布
