### ISSUE TITLE
导出的时候可以设置整行的背景颜色吗

### ISSUE THREAD

**Issue by danielv5** [wangguanquan/eec#235]
导出的时候，有时候校验这行数据存在错误，需要设置整行的背景色，提示这行数据有错误数据。这个要怎么实现呢？

**Comment by wangguanquan** [comment]
暂时没有可以直接使用的方法，需要做一些小改动。

**Comment by danielv5** [comment]
是需要修改源代码吗？还是可以有扩展点可以添加代码？有考虑添加这样的扩展方法吗？

**Comment by wangguanquan** [comment]
需要修改源代码增加这个功能点，如果有兴趣的话可以按下面的方法添加一个新功能。

方式1
1. 在entry包Sheet类添加一个abstract方法用于检查行数据 
2. 自定义一个Worksheet类继承Sheet类，并修改resetBlockData方法中调用上面定义的方法
3. 根据检查结果重置cell的xf值（添整为高亮色）

方式2
1. 在Sheet类定义一个java.util.function.Predicate属性用于整行数据检查
2. 修改现有子类resetBlockData方法中调用上面定义的方法
3. 根据检查结果重置cell的xf值（添整为高亮色）

修改好后可以提pull request，代码review通过后会并合并到主分支。欢迎提交代码

**Comment by wangguanquan** [comment]
更倾向用方式2，比起方式1更加方便和灵活。

**Comment by wangguanquan** [comment]
使用v0.5.2 可实现，具体可参考Wiki[动态设置样式](https://github.com/wangguanquan/eec/wiki/%E5%8A%A8%E6%80%81%E8%AE%BE%E7%BD%AE%E6%A0%B7%E5%BC%8F)
