### ISSUE TITLE
导出自定义注解和导入自定义注解

### ISSUE THREAD

**Issue by danielv5** [wangguanquan/eec#237]
你好，之前使用自定义注解。有发现如果使用自定义注解导出，但是导入注解还是使用官网的类。这样可能就会一个PO对象需要同时用自定义的注解和官网的注解。

**Comment by wangguanquan** [comment]
有具体的例子吗？

发自我的 iPhone

**Comment by danielv5** [comment]
主要是扩展ExcelColumn注解的功能，一个Java对象会有多个导出功能共用，但是导出的字段会存在一部分重合，一部分又不重合。所以有添加字段来区分使用方。这样导出功能通过自定义注解可以实现共用同一个对象。但是如果要导入还是用同一个对象，就需要在添加@ExcelColumn注解才能读取到数据

**Comment by wangguanquan** [comment]
有什么好想法吗？可以提一下

**Comment by wangguanquan** [comment]
目前导出已实现自定义注解，[点击这里飞过去](https://github.com/wangguanquan/eec/wiki/%E9%AB%98%E7%BA%A7%E7%89%B9%E6%80%A7#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%B3%A8%E8%A7%A3)

**Comment by wangguanquan** [comment]
关于读取文件的自定义注解将在下个版本支持，目前处于测试阶段，有兴趣可以clone本项目，并切到分支 fix#237 ，然后使用命令 `mvn clean install` 安装0.4.15-SNAPSHOT包，在测试工程引用此版本，就可以测试自定义注解了。可以参考测试代码 CustomAnnoReaderTest
