### ISSUE TITLE
excel 尾部有空行情况下没有能去除，同时提示IndexOutOfBoundsException

### ISSUE THREAD

**Issue by q459997705** [wangguanquan/eec#243]
![image](https://user-images.githubusercontent.com/4567701/167059577-f7e67088-be34-43a7-9fa2-ca36879d3f5f.png)
我的excel只有一千行，但是解析出来显示有5169行，原因是解析excel是发现尾部有空行和空列，会导致此异常，同时如果我将这部分数据复制到一个新的excel时候，解析是正常的
debug是发现会出现多出空列
![image](https://user-images.githubusercontent.com/4567701/167062202-d870adf8-eec5-4675-9ea7-ca28bac60d2d.png)
实际列
![image](https://user-images.githubusercontent.com/4567701/167062414-1790bbfd-e4d2-4646-8ce4-568b27e79bc4.png)

具体的代码如下
![image](https://user-images.githubusercontent.com/4567701/167059898-70c56875-8bd3-4d2c-bd55-281ea6c2eea2.png)

**Comment by q459997705** [comment]
代码如下
![Uploading image.png…]()

**Comment by wangguanquan** [comment]
IOOB这是一个已知问题，可以下载master，引用0.4.15-SNAPSHOT 本地试试

发自我的 iPhone

**Comment by q459997705** [comment]
> IOOB这是一个已知问题，可以下载master，引用0.4.15-SNAPSHOT 本地试试 发自我的 iPhone
> […](#)
> 在 2022年5月6日，11:00，q459997705 ***@***.***> 写道： 代码如下 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

我尝试下载master ，引用为0.4.15-SNAPSHOT 本地尝试 还是出现同样的问题。

**Comment by wangguanquan** [comment]
> 异常信息的5169不是指行，是指SharedString，SharedString是根据下标取数据，出问题是因为有空标签导致。

> 至于空行的判断，dataRow会过滤不包含任何内容的行，这里的内容包含格式化，样式等信息。

你也可以将文件发到我邮箱，包含的敏感信息使用abc代替。邮箱 guanquan.wang @ yandex.com

**Comment by q459997705** [comment]
现在将出现问题的excel,发送给你，具体excel在附件当中。麻烦您排查下


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangguanquan/eec"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月6日(星期五) 下午3:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangguanquan/eec] excel 尾部有空行情况下没有能去除，同时提示IndexOutOfBoundsException (Issue #243)





  
异常信息的5169不是指行，是指SharedString，SharedString是根据下标取数据，出问题是因为有空标签导致。
   
至于空行的判断，dataRow会过滤不包含任何内容的行，这里的内容包含格式化，样式等信息。
  
你也可以将文件发到我邮箱，包含的敏感信息使用abc代替。邮箱 guanquan.wang @ yandex.com

**Comment by wangguanquan** [comment]
没有收到测试文件

**Comment by q459997705** [comment]
重新发了一下，这次能收到么。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangguanquan/eec"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月6日(星期五) 晚上10:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangguanquan/eec] excel 尾部有空行情况下没有能去除，同时提示IndexOutOfBoundsException (Issue #243)





 
没有收到测试文件

**Comment by wangguanquan** [comment]
还是没有收到，或者你将文件上传到你的github项目中，我去下载。

**Comment by q459997705** [comment]
你可以从这个地址下载样例文件
https://github.com/q459997705/Grocery


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangguanquan/eec"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月6日(星期五) 晚上10:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangguanquan/eec] excel 尾部有空行情况下没有能去除，同时提示IndexOutOfBoundsException (Issue #243)





 
还是没有收到，或者你将文件上传到你的github项目中，我去下载。

**Comment by wangguanquan** [comment]
我看了一下，这个问题和 #226 一样，你可以切换分支到 fix#226 测试一下是否解决，该版本并未合并到master

**Comment by wangguanquan** [comment]
代码已合并可以pull master分支并重新测试
