### ISSUE TITLE
解析出的结果会有html标签

### ISSUE THREAD

**Issue by a444878151** [wangguanquan/eec#249]
![image](https://user-images.githubusercontent.com/13514068/175484665-01247964-e860-4758-975b-3cf840e65e8e.png)
[原始代码如上图，测试文件通过邮件发你

**Comment by wangguanquan** [comment]
测试文件已收到，周末抽时间解决

**Comment by a444878151** [comment]
辛苦，测试了性能，这个项目确实表现不错，我们这边使用的场景很多，也确实使用过程中有一些问题，希望大家一起改进。

**Comment by wangguanquan** [comment]
此BUG是由0.4.14版本引入，你可以先将版本回退到0.4.13

**Comment by wangguanquan** [comment]
拉取一下fix#249的分支试试看问题有没有解决

**Comment by wangguanquan** [comment]
v0.5.1 release
