### ISSUE TITLE
[Bug] [java.lang.NumberFormatException: empty String] 单元格为空时，没有判空，Double类型封装报空错误

### ISSUE THREAD

**Issue by YamMangoTea** [wangguanquan/eec#252]
![image](https://user-images.githubusercontent.com/46751423/176633051-2e699588-bf3b-4991-9671-fdcb31408446.png)

Main.java

    public List<People> testRead(String excelPath) {
            List<People> res = new ArrayList<>();
            try (ExcelReader reader = ExcelReader.read(Paths.get(excelPath))) {
                Sheet sheet = reader.sheet(0);
                Iterator<Row> ite = sheet.dataIterator();
                while (ite.hasNext()) {
                    People people = ite.next().to(People.class);
                    if (people.getName().equals("XXXX")){
                        res.add(people);
                    }
                }
                return res;
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
 
People.java

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public class People {
        private String name;
        private Date birthday;
        private Double money;
    
        public People(String name) {
            this.name= name;
        }
    }

**Comment by wangguanquan** [comment]
已在其它分支修改，fork本项目切换分支到 fix#210 然后本地打包可测试

**Comment by wangguanquan** [comment]
v0.5.1 release
