### ISSUE TITLE
出错时应该报出所在行列位置

### ISSUE THREAD

**Issue by apollo47** [wangguanquan/eec#284]
1、当读Excel，在转换成对象时，可能会因为多个空格等原因导致转换出错，这时应该错误信息应该要包含所在行，列，cell中的内容，以便查检Excel进行修改；

**Comment by apollo47** [comment]
2、当Excel没有标题行时，读不到第1行的数据（rows().map或dataRows().map()），建议标题行数由外部指定；
3、ExcelColumn注解增加required属性，当required=true时，如果这列出现空值，抛异常（参考第1点）；

**Comment by apollo47** [comment]
![image](https://user-images.githubusercontent.com/21029524/185064360-f4688369-10a8-4fcb-9b1b-e8c039ba086f.png)

**Comment by wangguanquan** [comment]
关于第一个和第三个可否提一个PR

第2个问题，EEC默认将读到的第一行做为表头，如果使用rows.map转对象时会存在表头返回Null的情况，因为这一行被转为HeaderRow，一般使用filter处理即可。例如文件前4行为其它数据，从第5行开始为表格，那么可以使用如下代码
`reader.sheet(0).rows().filter(row -> row.getRowNum() >= 5).map(row -> row.to(E.class)).filter(Objects::nonNull)`

**Comment by apollo47** [comment]
filter可以解决标题行数大于1的情况。但当没有标题行时（第1行就是实际业务数据），无法处理。可能你觉得加个标题行就可以。但实现上，Excel可能是由另一系统产生的，这中间全自动的，没有人为干预过程。

**Comment by wangguanquan** [comment]
如果没有表头的话就无法使用默认的`row#to`方法转实体，你可以使用更基础的方法，可以查看[jdbc方式读取](https://github.com/wangguanquan/eec/wiki/2-%E8%AF%BB%E5%8F%96Excel#jdbc%E6%96%B9%E5%BC%8F%E8%AF%BB%E5%8F%96)

**Comment by wangguanquan** [comment]
> filter可以解决标题行数大于1的情况。但当没有标题行时（第1行就是实际业务数据），无法处理。可能你觉得加个标题行就可以。但实现上，Excel可能是由另一系统产生的，这中间全自动的，没有人为干预过程。

对于2这种情况现有功能可以实现的，我之前一时也没有想起来，你可以使用`Sheet#bind`方法绑定Java对象（可以通过colIndex映射列)，然后调用row#get方法即可

```
// 无表头将行数据转为对象
List<Goods> list = reader.sheet(0).bind(Goods.class).rows().map(row -> (Goods) row.get()).collect(Collectors.toList());

// 第8行开始为表格数据时增加filter即可
List<Goods> list = reader.sheet(0).bind(Goods.class).rows().filter(row -> row.getRowNum() > 7).map(row -> (Goods) row.get()).collect(Collectors.toList());
```

详细请参考[WIKI](https://github.com/wangguanquan/eec/wiki/2-%E8%AF%BB%E5%8F%96Excel) 稍后我会补足详细代码

**Comment by wangguanquan** [comment]
v0.5.5 新增功能`Row#to`和`Row#too`方法转对象时如果异常将会提示出错单元格的行列信息
