### ISSUE TITLE
如何去掉斑马线？

### ISSUE THREAD

**Issue by liuziyuan** [wangguanquan/eec#300]
请问什么API可以快速去掉斑马线。
这个功能我认为不应该强加在默认的导出，而是应该提供一个方法。

**Comment by wangguanquan** [comment]
调用`cancelOddFill()`方法，更多使用方法可以查看[WIKI](https://github.com/wangguanquan/eec/wiki)

**Comment by liuziyuan** [comment]
感谢你的回复，我刚自己也找到了在wiki里。非常感谢
