### ISSUE TITLE
celltype的支持fomula，可以返回fomula公式字符和计算结果，以及数值类型优化为numeric，更贴切excel模式

### ISSUE THREAD

**Issue by zxj518** [wangguanquan/eec#33]

**Comment by zxj518** [comment]
This feature has been implements yet?

**Comment by wangguanquan** [comment]
v0.4.0 修复此问题。在打开Excel时传入2或者调用`ExcelReader#parseFormula`方法使EEC解析单元格公式。

使用方法请参照`ExcelReaderTest#testFormula`和`ExcelReaderTest#testFormulaOption`方法。
