### ISSUE TITLE
0.56版本的XMLWorksheetWrite重置列宽时，ByteBuffer长度分配异常

### ISSUE THREAD

**Issue by latebrose** [wangguanquan/eec#330]
https://github.com/wangguanquan/eec/blob/master/src/main/java/org/ttzero/excel/entity/e7/XMLWorksheetWriter.java
中，ByteBuffer buffer = ByteBuffer.allocate(316 + columns.length * 80);
这一行316这个参数感觉是不对的，经常会导致最后一列的 position = findPosition(buffer, "width=\"") 找到错误的值，抛出BufferOverflowException

**Comment by wangguanquan** [comment]
有没有测试代码，我也感觉这里有问题，但是怎么都无法复现

**Comment by wangguanquan** [comment]
你可以关闭autoSize来临时规避该问题

**Comment by latebrose** [comment]
我需要用到autoSize，所以回退到0.55版本了。

在0.56的情况下，这段代码会报错
`
package com.example.demo;

import com.example.demo.domain.ServerReport;
import lombok.SneakyThrows;
import lombok.var;
import org.junit.jupiter.api.Test;
import org.ttzero.excel.entity.CustomListSheet;
import org.ttzero.excel.entity.ListSheet;
import org.ttzero.excel.entity.Workbook;

import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

//@SpringBootTest
public class WriteTests {
    @Test
    @SneakyThrows
    public void test() {
        List<ServerReport> reports = new ArrayList();

        for (int i = 0; i < 1000; i++) {

            reports.add(ServerReport.builder()
                    .index(1 + i)
                    .clientRequestNum(i)
                    .name("测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试")
                    .duration(12345L)
                    .zipkinDt("22-07-07")
                    .timestamp(new Date())
                    .build());
        }

        System.out.println(new Date());

        var tmp = new Workbook("服务数据")
                .setAutoSize(true)
                .addSheet(new ListSheet("服务报表1", reports));
        tmp.writeTo(Paths.get("d://tmp/"));
        System.out.println(new Date());
    }
}
`

这是model的定义
`
package com.example.demo.domain;

import lombok.Builder;
import lombok.Data;
import org.ttzero.excel.annotation.ExcelColumn;
import org.ttzero.excel.annotation.FreezePanes;

import java.util.Date;

@Data
@Builder
@FreezePanes(topRow = 1)
public class ServerReport {

    @ExcelColumn(colIndex = 0, value = "序号")
    private Integer index;

    @ExcelColumn(colIndex = 2, value = "商户名")
    private String name;

    @ExcelColumn(colIndex = 1, value = "处理时间")
    private String zipkinDt;

    @ExcelColumn(colIndex = 3, value = "时间", format = "yyyy-mm-dd hh:mm:ss")
    private Date timestamp;

    @ExcelColumn(colIndex = 4, value = "请求次数")
    private Integer clientRequestNum;

    @ExcelColumn(colIndex = 5, value = "持续时间")
    private Long duration;
}

`

**Comment by wangguanquan** [comment]
拉取fix#330代码修复该BUG

**Comment by wangguanquan** [comment]
升级到v0.5.7 修复此BUG
