### ISSUE TITLE
【bug】 包含特殊字符的字符串写入，导致excel出错

### ISSUE THREAD

**Issue by 2259289435** [wangguanquan/eec#342]
示例：
SQYQDWMKG8164
其实是这个
SQ\u0004YQDWMKG8164

**Comment by wangguanquan** [comment]
放开`ExtBufferedWriter#escapeWrite`方法中的注释// UnDisplay char以下代码，原代码是将不可见字符去掉，当然你也可以像POI一样处理将不可见字符改写为[?]问号，只需要在128行加面加一行`write('?');`即可
