### ISSUE TITLE
动态列的导出问题

### ISSUE THREAD

**Issue by 89333367** [wangguanquan/eec#369]
目前在做大数据大数据导出，数据源是从hbase里读取数据，然后导出到excel中，hbase是列式存储，每一行的列有可能会不同，模拟了两行数据，第一行有两列A和B，第二行也有两列A和C，预期的导出结果应该是3列abc都有，但是导出发现，少了c列，如果手动循环所有行，将c填进去并且置空也能实现效果，但是效率太差了，有其他方案么？
**目前的导出代码**
```
@Test
    void t001() throws IOException {
        Workbook workbook = new Workbook();
        List<Map<String, ?>> rows = new ArrayList<>();
        rows.add(new HashMap<>() {{
            put("a", "1");
            put("b", "2");
        }});
        rows.add(new HashMap<>() {{
            put("a", "1");
            put("c", "3");
        }});
        workbook.addSheet(new ListMapSheet().setData(rows));
        workbook.writeTo(Paths.get("d:/tmp"));
    }
```
**发现导出后，缺少了c那一列**
![image](https://github.com/wangguanquan/eec/assets/20157752/524c41c4-20a6-4d3b-808f-e9dbfa4a1339)
**预期导出的结果是这样的**
![image](https://github.com/wangguanquan/eec/assets/20157752/470fd2f2-68d1-4b3d-ae67-148425f911c9)

**Comment by wangguanquan** [comment]
表头在第一行是最先写的，所以必须提前知道无法通过后面的数据添加在第一行上，EEC的设计与IO流一样游标只能向前。

如果列头已知的话可以穷举Column，或者你可以先收集表头
```
List<Column> columns = new ArrayList<>();
        columns.add(new Column("a"));
        columns.add(new Column("b"));
        columns.add(new Column("c"));
        new Workbook().setAutoSize(true)
            .addSheet(new ListSheet<>().setColumns(columns)).writeTo(Paths.get("./"));
```

**Comment by 89333367** [comment]
> 表头在第一行是最先写的，所以必须提前知道无法通过后面的数据添加在第一行上，EEC的设计与IO流一样游标只能向前。
> 
> 如果列头已知的话可以穷举Column，或者你可以先收集表头
> 
> ```
> List<Column> columns = new ArrayList<>();
>         columns.add(new Column("a"));
>         columns.add(new Column("b"));
>         columns.add(new Column("c"));
>         new Workbook().setAutoSize(true)
>             .addSheet(new ListSheet<>().setColumns(columns)).writeTo(Paths.get("./"));
> ```

嗯，这样子使用不了自动分页的more方法了。目前遇到问题是，每次从hbase取1万条，这时候，我可以循环一次，将title拿出来，把缺少的属性置空，但是拿下一页的时候，表头又变了，除非1万条一个sheet。目前实在是找不到好的方法解决。

**Comment by wangguanquan** [comment]
还可以自定义worksheet writer来处理，空了给你写个demo

在 2024年3月4日，08:42，SunYu ***@***.***> 写道：

﻿

表头在第一行是最先写的，所以必须提前知道无法通过后面的数据添加在第一行上，EEC的设计与IO流一样游标只能向前。

如果列头已知的话可以穷举Column，或者你可以先收集表头

List<Column> columns = new ArrayList<>();
        columns.add(new Column("a"));
        columns.add(new Column("b"));
        columns.add(new Column("c"));
        new Workbook().setAutoSize(true)
            .addSheet(new ListSheet<>().setColumns(columns)).writeTo(Paths.get("./"));


嗯，这样子使用不了自动分页的more方法了。目前遇到问题是，每次从hbase取1万条，这时候，我可以循环一次，将title拿出来，把缺少的属性置空，但是拿下一页的时候，表头又变了，除非1万条一个sheet。目前实在是找不到好的方法解决。

**Comment by wangguanquan** [comment]
请将你现有的示例代码贴出来吧，这样写出来的demo更符合你现在的需求

**Comment by 89333367** [comment]
> 请将你现有的示例代码贴出来吧，这样写出来的demo更符合你现在的需求

因为后面是hbase，每一行的列都不一样，没法提前知道有哪些列，所以下面代码导出的就少了D列

```
@Test
    void t003() throws IOException {
        new Workbook().addSheet(new ListMapSheet() {
            int page = 1;

            @Override
            protected List<Map<String, ?>> more() {
                return getRows(page++);
            }
        }).writeTo(Paths.get("d:/tmp"));//最终想要的结果是A/B/C/D列都有，如果超出范围自动分页
    }

    List<Map<String, ?>> getRows(int page) {
        if (page > 3) {
            return null;
        }
        List<Map<String, ?>> rows = new ArrayList<>();//模拟hbase中的数据，这里查询了hbase
        rows.add(new HashMap<>() {{//第一行，有A/B/C三列
            put("A", "a" + page);
            put("B", "b" + page);
            put("C", "c" + page);
        }});
        rows.add(new HashMap<>() {{//第二行有A/C/D三列
            put("A", "aa" + page);
            put("C", "c" + page);
            put("D", "d" + page);
        }});
        return rows;
    }
```

**Comment by wangguanquan** [comment]
第一步：自定义一个数据源，每行数据判断是否有不存在的key，如果有则追回到末尾
```
public static class AppendKeyMapSheet extends ListMapSheet {
        // 保存已存在中列
        Set<String> existsKeys = new HashSet<>();

        @Override
        public Column[] getHeaderColumns() {
            Column[] columns = super.getHeaderColumns();
            for (Column col : columns) existsKeys.add(col.name); // <- 初始化表头装载到existsKeys 
            return columns;
        }
        
        @Override
        protected void resetBlockData() {
            if (!eof && left() < rowBlock.capacity()) append();
            int end = getEndIndex(), len;
            for (; start < end; rows++, start++) {
                org.ttzero.excel.entity.Row row = rowBlock.next();
                row.index = rows;
                row.height = getRowHeight();
                Map<String, ?> rowDate = data.get(start);
                boolean isNull = rowDate == null;
                
                if (!isNull) {
                    // 检查是否有不存在的key
                    for (String k : rowDate.keySet()) {
                        if (!existsKeys.contains(k)) {
                           existsKeys.add(k);  // <- 将Key添加到existsKeys
                            Column col = new Column(k, k), pre = columns[columns.length - 1].getTail(); // <- 需要判断NPE
                            col.colIndex = pre.colIndex + 1;
                            col.realColIndex = pre.realColIndex + 1;
                            col.styles = getWorkbook().getStyles();
                            // 扩容并追加到末尾
                            columns = Arrays.copyOf(columns, columns.length + 1);
                            columns[columns.length - 1] = col;
                        }
                    }
                }
                len = columns.length;
                
                Cell[] cells = row.realloc(len);
                for (int i = 0; i < len; i++) {
                    Column hc = columns[i];
                    Object e = !isNull ? rowDate.get(hc.key) : null;
                    // Clear cells
                    Cell cell = cells[i];
                    cell.clear();

                    cellValueAndStyle.reset(row, cell, e, hc);
                }
            }
        }
    }
  ```

第二步自定义WorksheetWriter，在关闭流的时候特殊处理，重新写表头并将复制数据行（2次IO性能有所下降），也可以预流一定的空间只需要1次IO性能不受影响，需要的话可以联系

```
public static class AppendHeaderWorksheetWriter extends XMLWorksheetWriter {
    // 记录body的位置
    long position = 0L;
    @Override
    protected void beforeSheetData(boolean nonHeader) throws IOException {
        super.beforeSheetData(nonHeader);
        bw.flush(); // 刷新流

        // 获取当前position，从position以后开始写实际的body
        position = Files.size(workSheetPath.resolve(sheet.getFileName()));
    }

    @Override
    public void close() {
        super.close();

        XMLWorksheetWriter _writer = new XMLWorksheetWriter(sheet) {
            @Override protected boolean hasMedia() {
                return false;
            }
        };
        Class<XMLWorksheetWriter> clazz = XMLWorksheetWriter.class;
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        try {
            Field totalRowsField = clazz.getDeclaredField("totalRows");
            totalRowsField.setAccessible(true);
            totalRowsField.set(_writer, totalRows);
            Field startRowField = clazz.getDeclaredField("startRow");
            startRowField.setAccessible(true);
            startRowField.set(_writer, startRow - columns[0].subColumnSize());
            Field startHeaderRowField = clazz.getDeclaredField("startHeaderRow");
            startHeaderRowField.setAccessible(true);
            startHeaderRowField.set(_writer, startHeaderRow);
            Field includeAutoWidthField = clazz.getDeclaredField("includeAutoWidth");
            includeAutoWidthField.setAccessible(true);
            includeAutoWidthField.set(_writer, includeAutoWidth);
            Field stylesField = clazz.getDeclaredField("styles");
            stylesField.setAccessible(true);
            stylesField.set(_writer, styles);
            Field bwField = clazz.getDeclaredField("bw");
            bwField.setAccessible(true);
            BufferedWriter bw = new ExtBufferedWriter(new OutputStreamWriter(baos, StandardCharsets.UTF_8));
            bwField.set(_writer,  bw);
            // 重写col
            Method writeBeforeMethod = clazz.getDeclaredMethod("writeBefore");
            writeBeforeMethod.setAccessible(true);
            writeBeforeMethod.invoke(_writer);

            // 重写表头
            Method beforeSheetDataMethod = clazz.getDeclaredMethod("beforeSheetData", boolean.class);
            beforeSheetDataMethod.setAccessible(true);
            beforeSheetDataMethod.invoke(_writer, sheet.getNonHeader() == 1);

            bw.close();
        } catch (NoSuchFieldException | IllegalAccessException | InvocationTargetException | NoSuchMethodException | IOException e) {
            e.printStackTrace();
        }

        try {
            Path currentPath = workSheetPath.resolve(sheet.getFileName());
            String fileName = currentPath.getFileName().toString();
            // 创建临时文件
            Path tmpPath = Files.createFile(workSheetPath.resolve(fileName + "_cp"));
            // 将新表头复制到临时文件中
            try (SeekableByteChannel channel = Files.newByteChannel(tmpPath, StandardOpenOption.WRITE, StandardOpenOption.READ)) {
                ByteBuffer buffer = ByteBuffer.wrap(baos.toByteArray());
                buffer.order(ByteOrder.LITTLE_ENDIAN);
                channel.write(buffer);
            }

            // 将Body复制到临时文件中
            try (InputStream is = Files.newInputStream(currentPath);
                 OutputStream os = Files.newOutputStream(tmpPath, StandardOpenOption.APPEND)) {
                is.skip(position); // <- 跳到body处

                byte[] bytes = new byte[4096];
                int n;
                while ((n = is.read(bytes)) > 0) {
                    os.write(bytes, 0, n);
                }
            }

            // 替换现有文件
            Files.delete(currentPath);
            tmpPath.toFile().renameTo(currentPath.toFile());
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
```

导出的时候指定自定义数据源AppendKeyMapSheet和自定义输出协议AppendHeaderWorksheetWriter即可
```
@Test public void t003() throws IOException {
    new Workbook().addSheet(new AppendKeyMapSheet() { // <- 使用自定义数据源AppendKeyMapSheet
        int page = 1;

        @Override
        protected List<Map<String, ?>> more() {
            return getRows(page++);
        }
    }
    .setSheetWriter(new AppendHeaderWorksheetWriter())) // <- 使用自定义输出协议AppendHeaderWorksheetWriter
        .writeTo(Paths.get("d:/tmp"));//最终想要的结果是A/B/C/D列都有，如果超出范围自动分页
}

List<Map<String, ?>> getRows(int page) {
    if (page > 127 - 67) return null;
    List<Map<String, ?>> rows = new ArrayList<>();//模拟hbase中的数据，这里查询了hbase
    Map<String, Object> map = new HashMap<>();
    map.put("A", "a" + page);
    map.put("B", "b" + page);
    String key = new String(new char[] { (char) ('B' + page) });
    map.put(key, key + page);
    rows.add(map);
    return rows;
}
```

**Comment by 89333367** [comment]
> 第一步：自定义一个数据源，每行数据判断是否有不存在的key，如果有则追回到末尾
> 
> ```
> public static class AppendKeyMapSheet extends ListMapSheet {
>         // 保存已存在中列
>         Set<String> existsKeys = new HashSet<>();
> 
>         @Override
>         public Column[] getHeaderColumns() {
>             Column[] columns = super.getHeaderColumns();
>             for (Column col : columns) existsKeys.add(col.name); // <- 初始化表头装载到existsKeys 
>             return columns;
>         }
>         
>         @Override
>         protected void resetBlockData() {
>             if (!eof && left() < rowBlock.capacity()) append();
>             int end = getEndIndex(), len;
>             for (; start < end; rows++, start++) {
>                 org.ttzero.excel.entity.Row row = rowBlock.next();
>                 row.index = rows;
>                 row.height = getRowHeight();
>                 Map<String, ?> rowDate = data.get(start);
>                 boolean isNull = rowDate == null;
>                 
>                 if (!isNull) {
>                     // 检查是否有不存在的key
>                     for (String k : rowDate.keySet()) {
>                         if (!existsKeys.contains(k)) {
>                            existsKeys.add(k);  // <- 将Key添加到existsKeys
>                             Column col = new Column(k, k), pre = columns[columns.length - 1].getTail(); // <- 需要判断NPE
>                             col.colIndex = pre.colIndex + 1;
>                             col.realColIndex = pre.realColIndex + 1;
>                             col.styles = getWorkbook().getStyles();
>                             // 扩容并追加到末尾
>                             columns = Arrays.copyOf(columns, columns.length + 1);
>                             columns[columns.length - 1] = col;
>                         }
>                     }
>                 }
>                 len = columns.length;
>                 
>                 Cell[] cells = row.realloc(len);
>                 for (int i = 0; i < len; i++) {
>                     Column hc = columns[i];
>                     Object e = !isNull ? rowDate.get(hc.key) : null;
>                     // Clear cells
>                     Cell cell = cells[i];
>                     cell.clear();
> 
>                     cellValueAndStyle.reset(row, cell, e, hc);
>                 }
>             }
>         }
>     }
> ```
> 
> 第二步自定义WorksheetWriter，在关闭流的时候特殊处理，重新写表头并将复制数据行（2次IO性能有所下降），也可以预流一定的空间只需要1次IO性能不受影响，需要的话可以联系
> 
> ```
> public static class AppendHeaderWorksheetWriter extends XMLWorksheetWriter {
>     // 记录body的位置
>     long position = 0L;
>     @Override
>     protected void beforeSheetData(boolean nonHeader) throws IOException {
>         super.beforeSheetData(nonHeader);
>         bw.flush(); // 刷新流
> 
>         // 获取当前position，从position以后开始写实际的body
>         position = Files.size(workSheetPath.resolve(sheet.getFileName()));
>     }
> 
>     @Override
>     public void close() {
>         super.close();
> 
>         XMLWorksheetWriter _writer = new XMLWorksheetWriter(sheet) {
>             @Override protected boolean hasMedia() {
>                 return false;
>             }
>         };
>         Class<XMLWorksheetWriter> clazz = XMLWorksheetWriter.class;
>         ByteArrayOutputStream baos = new ByteArrayOutputStream();
>         try {
>             Field totalRowsField = clazz.getDeclaredField("totalRows");
>             totalRowsField.setAccessible(true);
>             totalRowsField.set(_writer, totalRows);
>             Field startRowField = clazz.getDeclaredField("startRow");
>             startRowField.setAccessible(true);
>             startRowField.set(_writer, startRow - columns[0].subColumnSize());
>             Field startHeaderRowField = clazz.getDeclaredField("startHeaderRow");
>             startHeaderRowField.setAccessible(true);
>             startHeaderRowField.set(_writer, startHeaderRow);
>             Field includeAutoWidthField = clazz.getDeclaredField("includeAutoWidth");
>             includeAutoWidthField.setAccessible(true);
>             includeAutoWidthField.set(_writer, includeAutoWidth);
>             Field stylesField = clazz.getDeclaredField("styles");
>             stylesField.setAccessible(true);
>             stylesField.set(_writer, styles);
>             Field bwField = clazz.getDeclaredField("bw");
>             bwField.setAccessible(true);
>             BufferedWriter bw = new ExtBufferedWriter(new OutputStreamWriter(baos, StandardCharsets.UTF_8));
>             bwField.set(_writer,  bw);
>             // 重写col
>             Method writeBeforeMethod = clazz.getDeclaredMethod("writeBefore");
>             writeBeforeMethod.setAccessible(true);
>             writeBeforeMethod.invoke(_writer);
> 
>             // 重写表头
>             Method beforeSheetDataMethod = clazz.getDeclaredMethod("beforeSheetData", boolean.class);
>             beforeSheetDataMethod.setAccessible(true);
>             beforeSheetDataMethod.invoke(_writer, sheet.getNonHeader() == 1);
> 
>             bw.close();
>         } catch (NoSuchFieldException | IllegalAccessException | InvocationTargetException | NoSuchMethodException | IOException e) {
>             e.printStackTrace();
>         }
> 
>         try {
>             Path currentPath = workSheetPath.resolve(sheet.getFileName());
>             String fileName = currentPath.getFileName().toString();
>             // 创建临时文件
>             Path tmpPath = Files.createFile(workSheetPath.resolve(fileName + "_cp"));
>             // 将新表头复制到临时文件中
>             try (SeekableByteChannel channel = Files.newByteChannel(tmpPath, StandardOpenOption.WRITE, StandardOpenOption.READ)) {
>                 ByteBuffer buffer = ByteBuffer.wrap(baos.toByteArray());
>                 buffer.order(ByteOrder.LITTLE_ENDIAN);
>                 channel.write(buffer);
>             }
> 
>             // 将Body复制到临时文件中
>             try (InputStream is = Files.newInputStream(currentPath);
>                  OutputStream os = Files.newOutputStream(tmpPath, StandardOpenOption.APPEND)) {
>                 is.skip(position); // <- 跳到body处
> 
>                 byte[] bytes = new byte[4096];
>                 int n;
>                 while ((n = is.read(bytes)) > 0) {
>                     os.write(bytes, 0, n);
>                 }
>             }
> 
>             // 替换现有文件
>             Files.delete(currentPath);
>             tmpPath.toFile().renameTo(currentPath.toFile());
>         } catch (IOException e) {
>             e.printStackTrace();
>         }
>     }
> }
> ```
> 
> 导出的时候指定自定义数据源AppendKeyMapSheet和自定义输出协议AppendHeaderWorksheetWriter即可
> 
> ```
> @Test public void t003() throws IOException {
>     new Workbook().addSheet(new AppendKeyMapSheet() { // <- 使用自定义数据源AppendKeyMapSheet
>         int page = 1;
> 
>         @Override
>         protected List<Map<String, ?>> more() {
>             return getRows(page++);
>         }
>     }
>     .setSheetWriter(new AppendHeaderWorksheetWriter())) // <- 使用自定义输出协议AppendHeaderWorksheetWriter
>         .writeTo(Paths.get("d:/tmp"));//最终想要的结果是A/B/C/D列都有，如果超出范围自动分页
> }
> 
> List<Map<String, ?>> getRows(int page) {
>     if (page > 127 - 67) return null;
>     List<Map<String, ?>> rows = new ArrayList<>();//模拟hbase中的数据，这里查询了hbase
>     Map<String, Object> map = new HashMap<>();
>     map.put("A", "a" + page);
>     map.put("B", "b" + page);
>     String key = new String(new char[] { (char) ('B' + page) });
>     map.put(key, key + page);
>     rows.add(map);
>     return rows;
> }
> ```

嗯，多谢大佬。我先按照这个思路搞一下。以后这个最好是你官方支持一下就好了，略微牺牲一点性能，做个开关之类的，毕竟针对大数据的导出，就排除不了现在的列式存储数据库，在未知有多少列、并且会动态列的情况下导出，这个功能估计也会不少

**Comment by wangguanquan** [comment]
EEC不考虑添加与业务相关的任何逻辑，有可能的话会添加一个ext工程，收集issue里的需求做成官方的扩展，有需要的话可以添加ext依赖使用

**Comment by 89333367** [comment]
> EEC不考虑添加与业务相关的任何逻辑，有可能的话会添加一个ext工程，收集issue里的需求做成官方的扩展，有需要的话可以添加ext依赖使用

嗯，扩展依赖合理。

**Comment by wangguanquan** [comment]
> > EEC不考虑添加与业务相关的任何逻辑，有可能的话会添加一个ext工程，收集issue里的需求做成官方的扩展，有需要的话可以添加ext依赖使用
> 
> 嗯，扩展依赖合理。

包含你的另一个issue #370 也适用一些简单导出场景也可以放到ext里

**Comment by 89333367** [comment]
> > > EEC不考虑添加与业务相关的任何逻辑，有可能的话会添加一个ext工程，收集issue里的需求做成官方的扩展，有需要的话可以添加ext依赖使用
> > 
> > 
> > 嗯，扩展依赖合理。
> 
> 包含你的另一个issue #370 也适用一些简单导出场景也可以放到ext里


嗯，其实针对这个动态列的问题，我也有一点想法，就是不会扩展
这个想法是之前我用其他工具类的时候的解决方法，效率不好，而且要保存后，重新开启excel更改表头

```
LinkedHashSet<String> titles = new LinkedHashSet<>();//用来保存所有列头
        List<Map<String, ?>> hbaseDatas = new ArrayList<>();//模拟hbase中的数据
        hbaseDatas.add(new HashMap<>() {{//第一行，有A/B/C三列
            put("A", "a" + 1);
            put("B", "b" + 1);
            put("C", "c" + 1);
        }});
        hbaseDatas.add(new HashMap<>() {{//第二行有A/C/D三列
            put("A", "aa" + 2);
            put("D", "d" + 2);
            put("C", "c" + 2);
        }});
        hbaseDatas.add(new HashMap<>() {{//第一行，有B/C两列
            put("B", "b" + 1);
            put("C", "c" + 1);
        }});
        for (Map<String, ?> row : hbaseDatas) {//循环所有行，填充列头对象
            for (String title : row.keySet()) {
                titles.add(title);
            }
        }
        log.info("{}", titles);//这里写入第一行表头，示例就打印一下

        List<Map<String, ?>> rows = new ArrayList<>();//重新组织数据，带顺序
        for (Map<String, ?> hbaseData : hbaseDatas) {
            Map<String, Object> row = new HashMap<>();
            for (String title : titles) {//重新组织数据，按照列顺序
                if (!hbaseData.containsKey(title)) {
                    //这个列这一行数据中不存在，将值置空
                    row.put(title, null);
                } else {
                    row.put(title, hbaseData.get(title));
                }
            }
            rows.add(row);
        }
        for (Map<String, ?> row : rows) {
            log.info("{}", row);
        }
        //这里将rows重新组织后，有列顺序的数据，写入excel，然后保存文件，再打开文件，将第一行表头titles重写一次，因为第二页翻页的时候，列头可能又增加了，重写表头后保存
```

**Comment by wangguanquan** [comment]
可以将两种方式导出的数据进行比较一下，如果数据源本身就是非格式化的那么表头顺序就是无法保证的，columns是数组本身是有序的，但无法预测下一次数据是包含哪个未知的title，所以添加到columns也是未知的。

**Comment by 89333367** [comment]
嗯，你给的方法我已经用上了。很好用，就是有一点
AppendKeyMapSheet类必须建立在org.ttzero.excel.entity包里面，否则会报
方法 AppendKeyMapSheet.resetBlockData()使用 package-private 字段Row.index

**Comment by wangguanquan** [comment]
可以直接调用row#getIndex()方法

**Comment by 89333367** [comment]
> 可以直接调用row#getIndex()方法 Message ID: ***@***.***>

```
org.ttzero.excel.entity.Row row = rowBlock.next();
            row.index = rows;   //这里是setIndex？没有这个方法呢
            row.height = getRowHeight();
```

**Comment by 89333367** [comment]
> 那是比较麻烦，下个版本将改为public，目前可以放在eec包下或者使用反射 Message ID: ***@***.***>

好的。期待下一个版本。
