### ISSUE TITLE
org.ttzero.excel.processor.Converter#reversion使用

### ISSUE THREAD

**Issue by keyang-wu** [wangguanquan/eec#376]
org.ttzero.excel.processor.Converter#reversion 入参能不能考虑把类型信息加上或者具有扩展性

<img width="850" alt="image" src="https://github.com/wangguanquan/eec/assets/54386652/2ae3f272-24c7-4c30-af39-d138292612b2">

碰到的场景是，导入从excel是从中文转成枚举类型

想针对所有枚举做一个单独的转换类，但是多个枚举定义的中文是有可能相同的，没办法只根据一个中文确定是哪个枚举类，又不想每个枚举单独定义

**Comment by wangguanquan** [comment]
可提交PR，新增Class参数

**Comment by keyang-wu** [comment]
Can't create a new pull request: Push failed: remote: Permission to wangguanquan/eec.git denied to keyang-wu. unable to access 'https://github.com/wangguanquan/eec.git/': The requested URL returned error: 403

**Comment by wangguanquan** [comment]
提交PR的步骤

1. fork本项目
2. 从你自己的仓库拉取代码
3. 切换分支修改代码和测试
4. push到你自己的仓库
5. 创建pull requests请求合并到主仓并等待合并

**Comment by keyang-wu** [comment]
好的👌

**Comment by keyang-wu** [comment]
这个v0.5.16是什么时候上啊

**Comment by wangguanquan** [comment]
近期吧

**Comment by wangguanquan** [comment]
需要紧急使用的话可以推SNAPSHOT到你们的私仓，发版后再切换正式版本

**Comment by keyang-wu** [comment]
没事 等正式版本发布吧
