### ISSUE TITLE
Q：Excel少列数导致数组下标越界问题？

### ISSUE THREAD

**Issue by tengfei2233** [wangguanquan/eec#380]
* 就是我导入一个Excel，表头位于第一行，共22列，但是第一列和第二列从数据行开始都是空白的，但是读取出来的Excel的Row通过toString打印，空白的部分有的是null，有的啥都没有直接跳过了，导致使用toMap转换就出现了数组下标越界问题。

* ![image](https://github.com/user-attachments/assets/f2e91cdc-6f98-4f05-aae1-b1a4e81c54d9)

* 还请作者大大看看是啥问题

**Comment by wangguanquan** [comment]
感谢你的反馈，这里有个逻辑漏洞，原代码里如果有表头就取表头的列范围，但表头并不能与body完全对齐造成越界。
临时处理你可以clone本项目然后修改Row类1345行Cell c = cells[i]需要改为Cell c = getCell(i)。修改后推到你自己的私仓并提交pullrequest

**Comment by wangguanquan** [comment]
我本地没有复现出来，请问使用`Cell c = getCell(i)`能解决这个问题吗？

**Comment by tengfei2233** [comment]
是的，我目前是可以的，可能更excel单元格格式有关，看着是空白的单元格，代码读取出来有的会显示null，有的没有任何东西，这样用toMap收集就和表头不对应了

**Comment by wangguanquan** [comment]
v0.5.17已修复
