### ISSUE TITLE
日期读取，转换到java类只能是yyyy-MM-dd HH:mm:ss格式吗

### ISSUE THREAD

**Issue by danielv5** [wangguanquan/eec#390]
Error occur in cell 'B2' value is "2024-09-01"(STRING). Timestamp format must be yyyy-mm-dd hh:mm:ss[.fffffffff]

**Comment by wangguanquan** [comment]
因为单元格是字符串，Java类里又定义为timestamp，所以默认走timestamp的格式化，你可以使用Converter或者定义一个set方法来处理都是可以的
