### ISSUE TITLE
【建议】希望将不创建对象的动态有序列的导出添加到Wiki示例教程中

### ISSUE THREAD

**Issue by LSL1618** [wangguanquan/eec#397]
很多时候导出列是由前端动态勾选哪些列和指定列顺序的，使用固定对象和列相关注解就不太适用了，这就很需要动态有序列的导出了。

**Comment by wangguanquan** [comment]
如果是前端传入的话可以按column的定义来接收参数，比如定义字段名，表头名，类型3个字段，导出的时候将前端选择的属性做为参数创建Column对象，这种动态勾选的在导出前已经确定头表的场景并不算是动态表头

```
// 接收前端传参
{"exportName":"", "columns";[{"key":"orderId", "name":"订单号"},{"key":"customer", "name":"客户名"},{"key":"tel", "name":"电话号码"}]}

public void export(Parmas params) {
    List<ExportColumnInfo> columns = params.getExportColumnInfos();
    List<Column> excelColumns = new ArrayList(columns.size());
    for (ExportColumnInfo ec : columns) {
        excelColumns.add(new Column(ec.getName(), ec.getKey()));
    }

    new Workbook().addSheet(new ListSheet<>(excelColumns)).writeTo(Paths.get("./" + params.getExportName()));
}
```

v0.5.20 提供SimpleSheet它支持不创建对象和HashMap，它支持使用setHeader设置表头且表头与body数据可以无任何关系，目前在测试中会在近期推送

```
List<Object> rows = new ArrayList<>();
rows.add(new String[]{"列1", "列2", "列3"});
rows.add(new int[]{1, 2, 3, 4});
rows.add(new Object[]{5, new Date(, 7, null, "字母", 9, 10.1243});

new Workbook()
    .addSheet(new SimpleSheet<>(rows).setHeader(Arrays.asList("表头1", "表头2"))) // 使用setHeader设置表头
    .writeTo(Paths.get("f:/excel"));
```

**Comment by wangguanquan** [comment]
> @wangguanquan 根据org.ttzero.excel.entity.Column类的结构来定义前端参数算是一种解决办法，只是目前的ListSheet跟对象是强绑定的，body数据不是对象封装的话就没法用了，ListMapSheet又是无序表头。新版的SimpleSheet预期功能倒是完美符合要求，不会被对象和注解限制死，期待新版本发布！

急用的话可以使用LinkedHashMap来保证顺序，ListMapSheet并不限制Map的实际类型

**Comment by LSL1618** [comment]
> > @wangguanquan 根据org.ttzero.excel.entity.Column类的结构来定义前端参数算是一种解决办法，只是目前的ListSheet跟对象是强绑定的，body数据不是对象封装的话就没法用了，ListMapSheet又是无序表头。新版的SimpleSheet预期功能倒是完美符合要求，不会被对象和注解限制死，期待新版本发布！
> 
> 急用的话可以使用LinkedHashMap来保证顺序，ListMapSheet并不限制Map的实际类型

这个倒是不急，不过这也是个解决方案。等等新版本吧！

**Comment by wangguanquan** [comment]
v0.5.20已推可以尝试是否可解决你的问题

**Comment by LSL1618** [comment]
> v0.5.20已推可以尝试是否可解决你的问题

可以的，已使用0.5.20版本。
