### ISSUE TITLE
拉不到依赖 Could not find artifact org.ttzero:eec:pom:3.5.7 in aliyun (https://maven.aliyun.com/repository/public)

### ISSUE THREAD

**Issue by SSSDNSY** [wangguanquan/eec#398]
阿里云和中央仓库都拉不到依赖，是我GAV有误，还是少了啥配置么？
Could not find artifact org.ttzero:eec:pom:3.5.7 in aliyun (https://maven.aliyun.com/repository/public)
![image](https://github.com/user-attachments/assets/891dabab-0748-4c87-bf38-0379619d6a5a)

![image](https://github.com/user-attachments/assets/6ebc77a4-be79-460c-8ab9-01dac4170a6f)

**Comment by wangguanquan** [comment]
没有这个版本，目前最新版本为0.5.19

**Comment by SSSDNSY** [comment]
OK，感谢答复，Issue 已关
