### ISSUE TITLE
对异步编程不太友好啊，有没有能单次写入数据的方法

### ISSUE THREAD

**Issue by zclcs** [wangguanquan/eec#401]

**Comment by wangguanquan** [comment]
没太明白单次写入数据是什么意思，异步编程的切入点在哪儿，你可以说得再详细一点吗？比如使用场景或伪代码来表明你想达成的效果

**Comment by zclcs** [comment]
> 没太明白单次写入数据是什么意思，异步编程的切入点在哪儿，你可以说得再详细一点吗？比如使用场景或伪代码来表明你想达成的效果

我看了一下源码，要改的话，代价挺大的
需求就是再用ListSheet setData 之后执行一次落盘
而不是最后在设置完所有数据后再落盘

**Comment by wangguanquan** [comment]
EEC将writeTo方法设计为终止操作符，在之前设置的所有属性均为临时属性，制作文件均在writeTo方法中实施。EEC使用RowBlock行块来收集行信息，默认32行刷一次盘。

setData 之后执行一次落盘的目地是做什么呢？你可以将整个导出的流程画一下，我看一下有没有可以简单改造的办法

**Comment by zclcs** [comment]
> EEC将writeTo方法设计为终止操作符，在之前设置的所有属性均为临时属性，制作文件均在writeTo方法中实施。EEC使用RowBlock行块来收集行信息，默认32行刷一次盘。
> 
> setData 之后执行一次落盘的目地是做什么呢？你可以将整个导出的流程画一下，我看一下有没有可以简单改造的办法

我这边用的vertx工具构建的应用
全异步的，不能阻塞主线程
![image](https://github.com/user-attachments/assets/bc350420-745f-4a28-80a3-81b520958afc)
这里是代码

**Comment by zclcs** [comment]
![image](https://github.com/user-attachments/assets/12784f29-bd85-4367-a3dd-e9d44c6118ad)

**Comment by zclcs** [comment]
![image](https://github.com/user-attachments/assets/3f538722-5b71-47b4-a546-8d273cb18f45)
我又改了一下，这样只会保存最后一次数据

**Comment by zclcs** [comment]
> setData只能在初始化的时候设置一次，可以放数据或者Supplier，设计之初确实没有想过这种使用场景，EEC目前不支持异步读写，如果只有1万左右数据的话可以先将数据取出来再setData，1万数据导出只需要几十毫秒。

![image](https://github.com/user-attachments/assets/c5d95bfc-9073-4ad6-9de7-4b27a125d78f)

嗯嗯，我又看了一遍源码，貌似只能把所有数据全加载出来再执行导出了

**Comment by zclcs** [comment]
> setData只能在初始化的时候设置一次，可以放数据或者Supplier，设计之初确实没有想过这种使用场景，EEC目前不支持异步读写，如果只有1万左右数据的话可以先将数据取出来再setData，1万数据导出只需要几十毫秒。

如果要改支持异步读写，能说下思路吗

**Comment by wangguanquan** [comment]
写数据均放在XMLWorkbookWriter和XMLWorksheetWriter文件里，WorkbookWriter为工作薄输出协议它会循环Worksheet并调用writeTo方法使用XMLWorksheetWriter写工作表内容，如果要支持异步的话就需要修改WorkbookWriter和XMLWorksheetWriter改起来确实比较麻烦，大部分方法都不是线程安全的，包含最基础的ExtBufferedWriter，在多线程下无法保证书写顺序。

EEC将数据源和输出协议分开设计，不同的输出协议可以实现不同格式输出，比如xlsx,xls和csv，目前只实现了xlsx和csv，不同数据源支持灵活取数。

**Comment by zclcs** [comment]
> 写数据均放在XMLWorkbookWriter和XMLWorksheetWriter文件里，WorkbookWriter为工作薄输出协议它会循环Worksheet并调用writeTo方法使用XMLWorksheetWriter写工作表内容，如果要支持异步的话就需要修改WorkbookWriter和XMLWorksheetWriter改起来确实比较麻烦，大部分方法都不是线程安全的，包含最基础的ExtBufferedWriter，在多线程下无法保证书写顺序。
> 
> 你可以尝试将XMLWorksheetWriter里的writeTo方法循环取数据的地方改为异步，nexBlock方法也需要改造，不必使用原方法直接取数即可
> 
> EEC将数据源和输出协议分开设计，不同的输出协议可以实现不同格式输出，比如xlsx,xls和csv，目前只实现了xlsx和csv，不同数据源支持灵活取数。

![image](https://github.com/user-attachments/assets/047b752d-ec16-4231-8638-ebadadbe856d)

我想重写一个ListSheet 但是有个org.ttzero.excel.entity.Sheet 有个属性是protected 访问不了

**Comment by wangguanquan** [comment]
在自定义sheet里添加一个set方法然后通过set方法来改

**Comment by zclcs** [comment]
> 在自定义sheet里添加一个set方法然后通过set方法来改 Message ID: ***@***.***>

的连着
