### ISSUE TITLE
如何扩展读写 workbook.xml 和 sheet*.xml 中的一些其它特性

### ISSUE THREAD

**Issue by zzmark** [wangguanquan/eec#406]
场景：
使用 TemplateSheet 渲染表格，模板表格设置了一些功能，这些功能目前没有被复制到生成的新表格中。

例如：
- 打印标题（位于 `workbook.xml: /definedNames/definedName#name="_xlnm.Print_Titles"`)
- 页边距（位于 `sheet.xml /pageMargins` ）

目前考虑过继承相关代码自行扩展，但很多类并不是 public，也没有找到其它方法。

**Comment by wangguanquan** [comment]
读取的话可以继承ExcelReader并覆写init方法，可以这里读取workbook.xml源码里已经读取了workbook.xml可以看一下，覆写sheetFactory方法可以传自定义XMLSheet并在自定义XMLSheet解析pageMargins节点。
写的话可以自定义XMLWorkbookWriter和XMLWorksheetWriter，如果遇到不可实现的方法可以将具体的方法贴出来。
