### ISSUE TITLE
同一行某一个单元格未填值时，报数组越界异常

### ISSUE THREAD

**Issue by Lizixiang** [wangguanquan/eec#81]
![image](https://user-images.githubusercontent.com/23308911/69206238-1a6c0a00-0b87-11ea-80d2-714e43e0e568.png)
同一行某一个单元格未填值时，报数组越界异常

**Comment by wangguanquan** [comment]
Fixed at version [V0.3.5](https://github.com/wangguanquan/eec/releases/tag/V0.3.5)
